# Generated by Django 3.1.1 on 2020-09-08 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='', max_length=150)),
                ('job_location', models.CharField(default='', max_length=150)),
                ('job_area', models.CharField(default='', max_length=150)),
                ('company', models.CharField(default='', max_length=150)),
                ('job_type', models.CharField(default='', max_length=150)),
                ('redirect_url', models.CharField(default='', max_length=150)),
                ('has_city', models.CharField(default='', max_length=150)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedjobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
