# Generated by Django 3.0.4 on 2020-08-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200815_1937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
