# Generated by Django 3.0.4 on 2020-09-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_savedjobs_has_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjobs',
            name='has_city',
            field=models.BooleanField(default=False),
        ),
    ]
