# Generated by Django 3.0.4 on 2020-09-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_savedjobs_has_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedjobs',
            name='has_city',
            field=models.CharField(default='', max_length=150),
        ),
    ]
